### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [theolundqvist/gears_cnc#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by theolundqvist** [comment]
> Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

You are free to use it as you wish. The ant colony optimization algorithm is not written by me as clarified by the code comments.

Glad i could help!

**Comment by theolundqvist** [comment]
Download the runnable .exe here: https://www.dropbox.com/sh/ssqr4q3f0iic6mi/AACE0E65xaUV96X30Gs2yC1Ka?dl=0

**Comment by suprafun** [comment]
Thank you so very much. Would it be possible for you to upload a formal license (e.g. MIT, BSD, GPL, whatever you prefer) to the repo. ? I ask because it would be nice for myself and others who might stumbled across this neat project, to know how we should treat it. Thank you.

**Comment by theolundqvist** [comment]
> Thank you so very much. Would it be possible for you to upload a formal license (e.g. MIT, BSD, GPL, whatever you prefer) to the repo. ? I ask because it would be nice for myself and others who might stumbled across this neat project, to know how we should treat it. Thank you.

Sure! Thanks for the positive response!
